global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'brs-kb'
    static_configs:
      - targets: ['brs-kb:8000']
    scrape_interval: 30s
    metrics_path: /metrics
